name: simple_bloc
description: A simplified library for creating stream-based bloc view models that adhere to the BLoC paradigm.
version: 0.0.1
author: andrew.ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/simple_bloc

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter