name: simple_bloc_todo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_bloc:
    path: ../../packages/simple_bloc
  uuid: 2.0.1
  intl: 0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
