name: simple_bloc_flutter
description: A simplified library for creating stream-based bloc view models that adhere to the BLoC paradigm. Includes Flutter widgets to integrate blocs into the Flutter ecosystem.
version: 0.1.0
author: andrew.ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/simple_bloc
repository: https://github.com/andrewackerman/simple_bloc
issue_tracker: https://github.com/andrewackerman/simple_bloc/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_bloc:
    path: ../simple_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter