name: simple_bloc_flutter
description: A new Dart package project.
version: 0.0.1
author: andrew.ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/simple_bloc

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_bloc:
    path: ../simple_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter