name: simple_flutter_counter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_bloc:
    path: ../../packages/simple_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
